version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        REQUIREMENTS_FILE: "requirements_back.txt"
    environment:
        REQUIREMENTS_FILE: requirements.txt
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
#      - worker_money

  db:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: "admin_pass"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "local"
    ports:
      - "5436:5436"
  redis:
    image: redis:5.0.8
    ports:
      - "6379:6379"
    volumes:
      - ./logs:/log
      - ./conf:/conf
  worker_money:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        REQUIREMENTS_FILE: "requirements.txt"
    environment:
      REQUIREMENTS_FILE: "requirements.txt"
#    command: ls ../../
    command: python manage.py runserver 0.0.0.0:8000

#    command: python worker_money.py


