# Generated by Django 3.2.9 on 2022-08-08 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Дата основания')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('last_price', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='PriceUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company')),
                ('current_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Актуальное время')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='company.company', verbose_name='Компания')),
            ],
        ),
    ]
